services:
  bd_mysql_mvp:
    image: mysql:8.0
    container_name: bd_mysql_mvp
    restart: always
    environment:
      TZ: "America/Mexico_City"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}    
      # MYSQL_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "3306:3306"
    volumes:
      - vol_mysql_mvp:/var/lib/mysql
    networks:
      - mvp_net
      - mvp_proxy
  app_mvp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_mvp
    ports:
    - "8080:80"

networks:
  mvp_net:
    external: true
  mvp_proxy:
    external: true

volumes:
  vol_mysql_mvp: