services:
  app_lab_piedad:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_lab_piedad
    ports:
    - "8080:80"

  bd_mysql_lab_piedad:
    image: mysql:8.0
    container_name: bd_mysql_lab_piedad
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_mysql_lab_piedad
    ports:
      - '3306:3306'
    volumes:
      - vol_lab_piedad:/var/lib/mysql  
    networks:
      - lab_piedad_net
      - lab_piedad_proxy

networks:
  lab_piedad_net:
    external: true   # Marca esta red como externa si ya existe
  lab_piedad_proxy:
    external: true

volumes:
  vol_lab_piedad:
