services:
  bd_mysql_lab_piedad:
    image: mysql:8.0
    container_name: bd_mysql_lab_piedad
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}    
      MYSQL_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "3306:3306"
    volumes:
      - vol_lab_piedad:/var/lib/mysql
    networks:
      - lab_piedad_net
      - lab_piedad_proxy
  app_lab_piedad:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_lab_piedad
    ports:
    - "8080:80"

networks:
  lab_piedad_net:
    external: true
  lab_piedad_proxy:
    external: true

volumes:
  vol_lab_piedad:
