name: CI/CD PHP Deploy VP

on:
  push:
    branches:
      - master

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands for PHP Docker app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "ConexiÃ³n exitosa al servidor"

            cd ${{ secrets.WORK_DIR }}
            echo "ðŸ“¥ Actualizando repositorio..."
            git fetch origin ${{ secrets.MAIN_BRANCH }}
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull origin ${{ secrets.MAIN_BRANCH }}

            composer i
            npm i
            npm run build

            echo "âœ… Despliegue completado en $HOSTNAME"
            echo "âœ… Despliegue completado en $HOSTNAME"

